twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    
    globals:
        app_name: '%env(APP_NAME)%'
        app_description: '%env(APP_DESCRIPTION)%'
        app_favicon: '%env(APP_FAVICON)%'
        app_banner: '%env(APP_BANNER)%'
        language_name: '%env(APP_LANGUAGE_NAME)%'
        original_language_name: '%env(APP_ORIGINAL_LANGUAGE_NAME)%'

when@test:
    twig:
        strict_variables: true