vich_uploader:
    db_driver: orm

    mappings:
        document_files:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        settings_banner:
            uri_prefix: /uploads/settings
            upload_destination: '%kernel.project_dir%/public/uploads/settings'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        settings_favicon:
            uri_prefix: /uploads/settings
            upload_destination: '%kernel.project_dir%/public/uploads/settings'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
